name: luncliff-vcpkg-tool
summary: "Experiment for deploying vcpkg executable to https://snapcraft.io/"
description: |
  Using a fork of https://github.com/microsoft/vcpkg-tool
  Check https://github.com/luncliff/vcpkg-tool-snapcraft together

base: core22
grade: devel
version: "test"
confinement: strict

parts:
  vcpkg:
    plugin: cmake
    source: https://github.com/luncliff/vcpkg-tool.git
    source-branch: develop # 4697044ee78033dcb38c68b536b0c96a07e887c1, 41ea97d040245007c2978d05955376edae521adb
    # source: https://github.com/microsoft/vcpkg-tool.git
    # source-tag: "2024-04-23"
    source-type: git
    source-depth: 1
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/local
      - -DCMAKE_C_COMPILER=clang-15
      - -DCMAKE_CXX_COMPILER=clang++-15
      - -DBUILD_TESTING=OFF
      - -DVCPKG_DEVELOPMENT_WARNINGS=OFF
      - -DVCPKG_EMBED_GIT_SHA=ON
      - -DVCPKG_DEPENDENCY_EXTERNAL_FMT=OFF
      - -DFMT_INSTALL=OFF
    build-packages:
      - git
      - clang-15
      - libc++-15-dev
    stage-packages:
      - git
      - curl
      - zip
      - unzip
      - tar
  upstream-registry:
    plugin: dump
    source: https://github.com/microsoft/vcpkg/archive/refs/tags/2024.04.26.zip
    source-type: zip
    organize:
      'vcpkg-2024.04.26' : usr/share/vcpkg

apps:
  vcpkg:
    command: /usr/local/bin/vcpkg --x-buildtrees-root $SNAP_USER_DATA/buildtrees --x-packages-root $SNAP_USER_DATA/packages --x-install-root $SNAP_USER_DATA/installed
    environment:
      VCPKG_ROOT: $SNAP/usr/share/vcpkg
      VCPKG_DOWNLOADS: $SNAP_USER_DATA
      VCPKG_DEFAULT_BINARY_CACHE: $SNAP_USER_DATA
