name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: snapcraft-build

      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft-build.outputs.snap }}

      - name: "Run snap(install)"
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft-build.outputs.snap }}
        shell: bash

      - name: "Run apps(vcpkg)"
        id: app-run
        run: |
          luncliff-vcpkg-tool.vcpkg --help
          luncliff-vcpkg-tool.vcpkg search zlib
        shell: bash

      - name: "Run apps(vcpkg install)"
        id: app-run-install
        run: |
          luncliff-vcpkg-tool.vcpkg install zlib-ng --debug
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ steps.app-run.outcome == 'failure' || steps.app-run-install.outcome == 'failure' }}
        with:
          name: app-run
          path: |
            ${{ env.HOME }}/snap/luncliff-vcpkg-tool/**/*.log
            ${{ env.HOME }}/snap/luncliff-vcpkg-tool/**/*.txt
