name: Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: snapcraft-build

      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft-build.outputs.snap }}

      - name: "Run snap(install)"
        run: |
          sudo snap install --dangerous ${{ steps.snapcraft-build.outputs.snap }}
        shell: bash
